(function(A){
  A.auth = {
    user:null, profile:null,
    async init(){ if(!A.supabase) return; const {data}=await A.supabase.auth.getUser(); this.user=data.user||null; if(this.user) await this.loadProfile(); this.renderNav(); A.supabase.auth.onAuthStateChange(async()=>{ const r=await A.supabase.auth.getUser(); this.user=r.data.user||null; this.profile=null; if(this.user) await this.loadProfile(); this.renderNav(); A.router?.render(); }); },
    async loadProfile(){ const {data}=await A.supabase.from('profiles').select('*').eq('id',this.user.id).maybeSingle(); this.profile=data; return data; },
    async requireLogin(){ if(!this.user){ location.hash='#/login'; A.toast('Silakan login terlebih dahulu.'); return false;} return true; },
    async requireAdmin(){ if(!await this.requireLogin()) return false; await this.loadProfile(); if(this.profile?.role !== 'admin'){ A.toast('Admin only. Customer biasa tidak dapat mengakses route admin.'); location.hash='#/home'; return false;} return true; },
    renderNav(){ const auth=A.$('#authNav'); const admin=A.$('#adminNavButton'); if(!auth) return; if(this.user){ const name=this.profile?.full_name||this.user.email||'User'; auth.innerHTML=`<img class="avatar" src="${A.escape(this.profile?.avatar_url||'assets/logo.svg')}" alt="avatar"><button id="logoutButton" class="btn btn-ghost">Logout</button>`; A.$('#logoutButton')?.addEventListener('click',()=>this.logout()); } else auth.innerHTML='<a class="btn btn-ghost" href="#/login">Login</a><a class="btn btn-primary" href="#/register">Register</a>'; admin?.classList.toggle('hidden', this.profile?.role !== 'admin'); admin?.addEventListener('click',()=>location.hash='#/admin'); },
    loginView(){ return `<section class="section container"><div class="grid grid-2"><div><p class="eyebrow">Welcome back</p><h1>Login</h1><p class="lead">Masuk untuk checkout, tracking order realtime, dan menulis review.</p></div><form id="loginForm" class="card form"><label class="field">Email<input name="email" type="email" required></label><label class="field">Password<input name="password" type="password" required></label><button class="btn btn-primary">Login</button><button id="googleLogin" type="button" class="btn btn-ghost">Login with Google</button></form></div></section>`; },
    registerView(){ return `<section class="section container"><div class="grid grid-2"><div><p class="eyebrow">Join Amino</p><h1>Register</h1><p class="lead">Buat akun customer untuk booking dan order.</p></div><form id="registerForm" class="card form"><label class="field">Nama<input name="name" required></label><label class="field">Email<input name="email" type="email" required></label><label class="field">Password<input name="password" type="password" minlength="6" required></label><button class="btn btn-primary">Register</button></form></div></section>`; },
    profileView(){ const p=this.profile||{}; return `<section class="section container"><h1>Profile</h1>${this.user?`<div class="card form"><div class="profile-card"><img class="avatar" src="${A.escape(p.avatar_url||'assets/logo.svg')}" alt="avatar"><div><strong>${A.escape(p.full_name||this.user.email)}</strong><p>${A.escape(p.role||'customer')}</p></div></div><label class="field">Upload image<input id="avatarUpload" type="file" accept="image/*"></label><button id="saveProfile" class="btn btn-primary">Save setting</button></div>`:A.empty('Login untuk melihat profil.')}</section>`; },
    bindAuthForms(){ A.$('#loginForm')?.addEventListener('submit',async e=>{e.preventDefault(); const f=new FormData(e.target); const {error}=await A.supabase.auth.signInWithPassword({email:f.get('email'),password:f.get('password')}); if(error) return A.toast(error.message); location.hash='#/home';}); A.$('#registerForm')?.addEventListener('submit',async e=>{e.preventDefault(); const f=new FormData(e.target); const {error}=await A.supabase.auth.signUp({email:f.get('email'),password:f.get('password'),options:{data:{full_name:f.get('name')}}}); if(error) return A.toast(error.message); A.toast('Registrasi berhasil, cek email bila konfirmasi aktif.'); location.hash='#/login';}); A.$('#googleLogin')?.addEventListener('click',()=>A.supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+location.pathname}})); A.$('#saveProfile')?.addEventListener('click',()=>A.toast('Profile saved.')); A.$('#avatarUpload')?.addEventListener('change',e=>A.uploadAvatar(e.target.files[0])); },
    async logout(){ await A.supabase.auth.signOut(); location.hash='#/home'; }
  };
  A.uploadAvatar = async file => { if(!file||!A.auth.user) return; const path=`${A.auth.user.id}/${Date.now()}-${file.name}`; const {error}=await A.supabase.storage.from('avatars').upload(path,file,{upsert:true}); if(error) return A.toast(error.message); const {data}=A.supabase.storage.from('avatars').getPublicUrl(path); await A.supabase.from('profiles').update({avatar_url:data.publicUrl}).eq('id',A.auth.user.id); A.toast('Avatar uploaded.'); A.auth.init(); };
})(window.Amino = window.Amino || {});
