(function(A){
  const callbackUrl = () => `${window.location.origin}/auth/callback`;
  const hasAuthTokens = () => /access_token|refresh_token|type=signup|type=recovery|auth\/callback/.test(window.location.href);
  A.auth = {
    user:null, profile:null, orders:[], bookings:[], reviews:[], avatarFile:null, avatarPreview:null,
    async init(){
      if(!A.supabase) return;
      if(hasAuthTokens()) await this.handleCallback();
      const {data}=await A.supabase.auth.getUser();
      this.user=data.user||null;
      if(this.user) await this.loadProfile();
      this.renderNav();
      A.supabase.auth.onAuthStateChange(async(event)=>{ const r=await A.supabase.auth.getUser(); this.user=r.data.user||null; this.profile=null; if(this.user) await this.loadProfile(); this.renderNav(); if(event==='SIGNED_IN') A.toast('Login berhasil','success'); A.router?.render(); });
    },
    async handleCallback(){
      await new Promise(resolve=>setTimeout(resolve,350));
      history.replaceState({}, document.title, `${window.location.origin}${window.location.pathname.replace('/auth/callback','/') }#/profile`);
      A.toast('Login berhasil','success');
    },
    async loadProfile(){ const {data}=await A.supabase.from('profiles').select('*').eq('id',this.user.id).maybeSingle(); this.profile=data||{id:this.user.id,email:this.user.email,role:'customer'}; return this.profile; },
    async loadHistory(){ if(!this.user) return; const [orders,bookings,reviews]=await Promise.all([A.supabase.from('orders').select('*, order_items(*)').eq('user_id',this.user.id).order('created_at',{ascending:false}).limit(20), A.supabase.from('bookings').select('*').eq('user_id',this.user.id).order('created_at',{ascending:false}).limit(20), A.supabase.from('reviews').select('*').eq('user_id',this.user.id).order('created_at',{ascending:false}).limit(20)]); this.orders=orders.data||[]; this.bookings=bookings.data||[]; this.reviews=reviews.data||[]; },
    async requireLogin(){ if(!this.user){ location.hash='#/login'; A.toast('Silakan login terlebih dahulu.'); return false;} return true; },
    async requireAdmin(){ if(!await this.requireLogin()) return false; await this.loadProfile(); if(this.profile?.role !== 'admin'){ A.toast('Admin only. Customer biasa tidak dapat mengakses route admin.'); location.hash='#/home'; return false;} return true; },
    renderNav(){ const auth=A.$('#authNav'); const admin=A.$('#adminNavButton'); if(!auth) return; if(this.user){ const name=this.profile?.full_name||this.user.email||'User'; auth.innerHTML=`<a class="profile-chip" href="#/profile"><img class="avatar" src="${A.escape(this.profile?.avatar_url||this.avatarPreview||'assets/logo.svg')}" alt="avatar"><span>${A.escape(name.split('@')[0])}</span></a><button id="logoutButton" class="btn btn-ghost">Logout</button>`; A.$('#logoutButton')?.addEventListener('click',()=>this.logout()); } else auth.innerHTML='<a class="btn btn-ghost" href="#/login">Login</a><a class="btn btn-primary" href="#/register">Register</a>'; admin?.classList.toggle('hidden', this.profile?.role !== 'admin'); if(admin) admin.onclick=()=>location.hash='#/admin'; },
    loginView(){ return `<section class="section container auth-section"><div class="auth-copy"><p class="eyebrow">Welcome back</p><h1>Login Amino Resto Bali</h1><p class="lead">Masuk untuk checkout, WhatsApp order, tracking realtime, booking, dan review.</p><div class="notice">Redirect auth memakai origin domain aktif, bukan localhost.</div></div><form id="loginForm" class="card form auth-card"><label class="field">Email<input name="email" type="email" autocomplete="email" required></label><label class="field">Password<input name="password" type="password" autocomplete="current-password" required></label><button class="btn btn-primary">Login</button><button id="googleLogin" type="button" class="btn btn-ghost">Login with Google</button></form></section>`; },
    registerView(){ return `<section class="section container auth-section"><div class="auth-copy"><p class="eyebrow">Join Amino</p><h1>Register</h1><p class="lead">Email confirmation akan redirect ke <strong>${A.escape(callbackUrl())}</strong>.</p></div><form id="registerForm" class="card form auth-card"><label class="field">Nama<input name="name" required></label><label class="field">Phone<input name="phone" inputmode="tel"></label><label class="field">Email<input name="email" type="email" required></label><label class="field">Password<input name="password" type="password" minlength="6" required></label><button class="btn btn-primary">Register</button></form></section>`; },
    profileView(){ const p=this.profile||{}; if(!this.user) return `<section class="section container">${A.empty('Login untuk mengelola profile, order history, booking, dan review.')}</section>`; return `<section class="section container"><div class="section-head"><div><p class="eyebrow">Customer Profile</p><h1>My Amino</h1></div><button id="profileLogout" class="btn btn-ghost">Logout</button></div><div class="profile-layout"><form id="profileForm" class="card form"><div class="profile-card"><img id="avatarPreview" class="avatar big" src="${A.escape(this.avatarPreview||p.avatar_url||'assets/logo.svg')}" alt="avatar"><div><strong>${A.escape(p.full_name||this.user.email)}</strong><p>${A.escape(this.user.email)}</p></div></div><label class="field">Edit nama<input name="full_name" value="${A.escape(p.full_name||'')}"></label><label class="field">Edit phone<input name="phone" value="${A.escape(p.phone||'')}"></label><label class="field">Edit avatar upload<input id="avatarUpload" type="file" accept="image/*"></label><label class="field">Ganti password<input name="password" type="password" minlength="6" placeholder="Kosongkan jika tidak diganti"></label><button class="btn btn-primary">Save profile</button></form><div class="grid"><div class="card"><h2>Order history</h2>${this.orders.length?this.orders.map(o=>`<p><strong>#${o.id.slice(0,8)}</strong> ${A.escape(o.status)} · ${A.formatRupiah(o.total)}</p>`).join(''):A.empty('Belum ada order.')}</div><div class="card"><h2>Booking history</h2>${this.bookings.length?this.bookings.map(b=>`<p>${A.escape(b.booking_date)} ${A.escape(b.booking_time)} · ${A.escape(b.status)}</p>`).join(''):A.empty('Belum ada booking.')}</div><div class="card"><h2>Review saya</h2>${this.reviews.length?this.reviews.map(r=>`<div class="review-row"><p>${'★'.repeat(r.rating)} ${A.escape(r.comment)}</p>${(r.reply||r.admin_reply)?'<small>Sudah dibalas admin</small>':`<button class="btn btn-danger delete-own-review" data-id="${r.id}">Delete review</button>`}</div>`).join(''):A.empty('Belum ada review.')}</div></div></div></section>`; },
    bindAuthForms(){
      A.$('#loginForm')?.addEventListener('submit',async e=>{e.preventDefault(); const f=new FormData(e.target); const {error}=await A.supabase.auth.signInWithPassword({email:f.get('email'),password:f.get('password')}); if(error) return A.toast(error.message,'error'); location.hash='#/profile';});
      A.$('#registerForm')?.addEventListener('submit',async e=>{e.preventDefault(); const f=new FormData(e.target); const {error}=await A.supabase.auth.signUp({email:f.get('email'),password:f.get('password'),options:{data:{full_name:f.get('name'),phone:f.get('phone')},emailRedirectTo:callbackUrl()}}); if(error) return A.toast(error.message,'error'); await A.notifyFunction({type:'customer_register',customer_email:f.get('email'),customer_name:f.get('name')}); A.toast('Registrasi berhasil. Cek email untuk konfirmasi.'); location.hash='#/login';});
      A.$('#googleLogin')?.addEventListener('click',()=>A.supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:callbackUrl()}}));
      A.$('#avatarUpload')?.addEventListener('change',e=>{ const file=e.target.files[0]; if(!file) return; this.avatarFile=file; this.avatarPreview=URL.createObjectURL(file); const img=A.$('#avatarPreview'); if(img) img.src=this.avatarPreview; });
      A.$('#profileForm')?.addEventListener('submit',async e=>this.saveProfile(e));
      A.$('#profileLogout')?.addEventListener('click',()=>this.logout());
      A.$$('.delete-own-review').forEach(b=>b.addEventListener('click',async()=>{ const {error}=await A.supabase.from('reviews').delete().eq('id',b.dataset.id).is('reply',null).is('admin_reply',null); A.toast(error?error.message:'Review deleted', error?'error':'success'); A.router.render(); }));
    },
    async saveProfile(e){ e.preventDefault(); const f=new FormData(e.target); let avatar_url=this.profile?.avatar_url; if(this.avatarFile) avatar_url = await A.uploadAvatar(this.avatarFile, false) || avatar_url; const updates={full_name:f.get('full_name'),phone:f.get('phone'),avatar_url}; const {error}=await A.supabase.from('profiles').update(updates).eq('id',this.user.id); if(error) return A.toast(error.message,'error'); if(f.get('password')) { const pass=await A.supabase.auth.updateUser({password:f.get('password')}); if(pass.error) return A.toast(pass.error.message,'error'); } A.toast('Profile tersimpan','success'); await this.loadProfile(); this.renderNav(); },
    async logout(){ await A.supabase.auth.signOut(); location.hash='#/home'; }
  };
  A.uploadAvatar = async (file, reload=true) => { if(!file||!A.auth.user) return null; const path=`${A.auth.user.id}/${Date.now()}-${file.name.replace(/\s+/g,'-')}`; const {error}=await A.supabase.storage.from('avatars').upload(path,file,{upsert:true}); if(error){ A.toast(error.message,'error'); return null; } const {data}=A.supabase.storage.from('avatars').getPublicUrl(path); if(reload){ await A.supabase.from('profiles').update({avatar_url:data.publicUrl}).eq('id',A.auth.user.id); A.toast('Avatar uploaded.'); A.auth.init(); } return data.publicUrl; };
})(window.Amino = window.Amino || {});
