(function(A){
  A.cart = {
    items(){ return A.storage.getCart(); },
    add(item, variant){ if(!item) return; const chosen=variant || item.item_variants?.[0]; const id=`${item.id}:${chosen?.id||'base'}`; const price=chosen?.price||item.price||0; const cart=this.items(); const found=cart.find(x=>x.cart_id===id); if(found) found.qty++; else cart.push({cart_id:id,id:item.id,variant_id:chosen?.id,name:item.name,variant_name:chosen?.name||'',price,image_url:item.image_url,qty:1,note:''}); A.storage.saveCart(cart); A.toast('Added to cart','success'); },
    update(cartId,delta){ const cart=this.items().map(i=>i.cart_id===cartId?{...i,qty:i.qty+delta}:i).filter(i=>i.qty>0); A.storage.saveCart(cart); },
    setNote(cartId,note){ const cart=this.items().map(i=>i.cart_id===cartId?{...i,note}:i); A.storage.saveCart(cart); },
    summary(){ const subtotal=this.items().reduce((a,i)=>a+i.qty*i.price,0); return A.totals(subtotal); },
    render(){ const cart=this.items(); const count=cart.reduce((a,i)=>a+i.qty,0); const t=this.summary(); ['#cartBadge','#bottomCartBadge'].forEach(sel=>{ if(A.$(sel)) A.$(sel).textContent=count; }); if(A.$('#cartItems')) A.$('#cartItems').innerHTML=cart.length?cart.map(i=>`<div class="cart-row"><img src="${A.escape(i.image_url||A.placeholder())}" alt=""><div><strong>${A.escape(i.name)}</strong><p>${A.escape(i.variant_name)} · ${A.formatRupiah(i.price)}</p><textarea class="cart-note" data-id="${i.cart_id}" placeholder="Catatan item">${A.escape(i.note||'')}</textarea><div class="qty"><button class="icon-button cart-minus" data-id="${i.cart_id}">−</button><span>${i.qty}</span><button class="icon-button cart-plus" data-id="${i.cart_id}">+</button></div></div><strong>${A.formatRupiah(i.price*i.qty)}</strong></div>`).join(''):A.empty('Cart masih kosong.'); ['Subtotal','Tax','Service','Total'].forEach(k=>{ const el=A.$(`#cart${k}`); if(el) el.textContent=A.formatRupiah(t[k.toLowerCase()]); }); A.$$('.cart-minus').forEach(b=>b.addEventListener('click',()=>this.update(b.dataset.id,-1))); A.$$('.cart-plus').forEach(b=>b.addEventListener('click',()=>this.update(b.dataset.id,1))); A.$$('.cart-note').forEach(n=>n.addEventListener('change',()=>this.setNote(n.dataset.id,n.value))); },
    bind(){ A.$('#cartButton')?.addEventListener('click',()=>A.$('#cartDrawer').classList.add('open')); A.$('#bottomCart')?.addEventListener('click',()=>A.$('#cartDrawer').classList.add('open')); A.$('#closeCart')?.addEventListener('click',()=>A.$('#cartDrawer').classList.remove('open')); window.addEventListener('cart:changed',()=>this.render()); this.render(); },
    buildWhatsAppText(formData={}){ const user=A.auth?.profile||{}; const cart=this.items(); const t=this.summary(); const lines=['*AMINO RESTO BALI ORDER*','',`Nama: ${formData.customer_name||user.full_name||A.auth?.user?.email||'-'}`,`Nomor HP: ${formData.customer_phone||user.phone||'-'}`,`Tipe order: ${formData.order_type||'online'}`]; if(formData.table_number) lines.push(`Table: ${formData.table_number}`); if(formData.delivery_address) lines.push(`Alamat: ${formData.delivery_address}`); if(formData.delivery_lat && formData.delivery_lng) lines.push(`Lokasi Maps: https://maps.google.com/?q=${formData.delivery_lat},${formData.delivery_lng}`); lines.push('', '*Items:*'); cart.forEach(i=>lines.push(`- ${i.qty}x ${i.name}${i.variant_name?' ('+i.variant_name+')':''} @ ${A.formatRupiah(i.price)}${i.note?' — '+i.note:''}`)); lines.push('',`Subtotal: ${A.formatRupiah(t.subtotal)}`,`Tax 10%: ${A.formatRupiah(t.tax)}`,`Service 5%: ${A.formatRupiah(t.service)}`,`Total: ${A.formatRupiah(t.total)}`,`Payment: ${formData.payment_method||'Cash'}`,'','Notice: PRICES ARE NOT FIXED'); return lines.join('\n'); },
    view(){ const cart=this.items(); const t=this.summary(); return `<section class="section container checkout-section"><div class="section-head"><div><p class="eyebrow">Checkout Online / Offline</p><h1>Your Cart</h1><p>PRICES ARE NOT FIXED. Tax 10% dan service 5% diterapkan.</p></div><button id="copyCartText" class="btn btn-ghost">Copy Order Text</button></div><div class="checkout-layout"><div class="card cart-page-list">${cart.length?cart.map(i=>`<div class="cart-row"><img src="${A.escape(i.image_url||A.placeholder())}"><div><strong>${A.escape(i.name)}</strong><p>${A.escape(i.variant_name)} · ${i.qty} × ${A.formatRupiah(i.price)}</p><textarea class="cart-note" data-id="${i.cart_id}" placeholder="Catatan item">${A.escape(i.note||'')}</textarea></div><strong>${A.formatRupiah(i.qty*i.price)}</strong></div>`).join(''):A.empty('Tambahkan menu terlebih dahulu.')}</div><form id="checkoutForm" class="card form checkout-card"><h2>Place order</h2><label class="field">Nama pelanggan<input name="customer_name" value="${A.escape(A.auth.profile?.full_name||'')}" required></label><label class="field">Nomor HP<input name="customer_phone" value="${A.escape(A.auth.profile?.phone||'')}" required></label><label class="field">Order type<select id="orderType" name="order_type"><option value="dine_in">Dine In</option><option value="takeaway">Takeaway</option><option value="delivery">Delivery</option><option value="online">Online</option></select></label><label class="field dine-field">Table number<input name="table_number" placeholder="Wajib untuk dine in"></label><label class="field delivery-field hidden">Delivery address<textarea name="delivery_address" placeholder="Wajib untuk delivery"></textarea></label><div class="delivery-field hidden action-row"><button id="useLocation" type="button" class="btn btn-ghost">Use my location</button><input name="delivery_lat" type="hidden"><input name="delivery_lng" type="hidden"><small id="locationStatus"></small></div><label class="field">Payment<select name="payment_method"><option>Cash</option><option>QRIS</option><option>DANA</option><option>GoPay</option><option>Card</option></select></label><div class="qris-placeholder">QRIS belum diupload admin</div><label class="field">Catatan order<textarea name="notes"></textarea></label><div class="summary-box"><p>Subtotal ${A.formatRupiah(t.subtotal)}</p><p>Tax 10% ${A.formatRupiah(t.tax)}</p><p>Service 5% ${A.formatRupiah(t.service)}</p><h3>Total ${A.formatRupiah(t.total)}</h3></div><div class="action-row"><button class="btn btn-primary" ${cart.length?'':'disabled'}>Place order</button><button id="whatsappOrder" type="button" class="btn btn-secondary">WhatsApp Order</button><button id="saveWhatsapp" type="button" class="btn btn-ghost">Save Order & WhatsApp</button></div></form></div></section>`; }
  };
})(window.Amino = window.Amino || {});
