(function(A){
  A.cart = {
    items(){ return A.storage.getCart(); },
    add(item){ if(!item) return; const cart=this.items(); const price=item.item_variants?.[0]?.price||item.price||0; const found=cart.find(x=>x.id===item.id); if(found) found.qty++; else cart.push({id:item.id,name:item.name,price,image_url:item.image_url,qty:1}); A.storage.saveCart(cart); A.toast('Added to cart'); },
    update(id,delta){ const cart=this.items().map(i=>i.id===id?{...i,qty:i.qty+delta}:i).filter(i=>i.qty>0); A.storage.saveCart(cart); },
    render(){ const cart=this.items(); const count=cart.reduce((a,i)=>a+i.qty,0); const sub=cart.reduce((a,i)=>a+i.qty*i.price,0); const t=A.totals(sub); if(A.$('#cartBadge')) A.$('#cartBadge').textContent=count; if(A.$('#cartItems')) A.$('#cartItems').innerHTML=cart.length?cart.map(i=>`<div class="cart-row"><img src="${A.escape(i.image_url||A.placeholder())}" alt=""><div><strong>${A.escape(i.name)}</strong><p>${A.formatRupiah(i.price)}</p><div class="qty"><button class="icon-button cart-minus" data-id="${i.id}">−</button><span>${i.qty}</span><button class="icon-button cart-plus" data-id="${i.id}">+</button></div></div><strong>${A.formatRupiah(i.price*i.qty)}</strong></div>`).join(''):A.empty('Cart masih kosong.'); ['Subtotal','Tax','Service','Total'].forEach(k=>{ const el=A.$(`#cart${k}`); if(el) el.textContent=A.formatRupiah(t[k.toLowerCase()]); }); A.$$('.cart-minus').forEach(b=>b.addEventListener('click',()=>this.update(b.dataset.id,-1))); A.$$('.cart-plus').forEach(b=>b.addEventListener('click',()=>this.update(b.dataset.id,1))); },
    bind(){ A.$('#cartButton')?.addEventListener('click',()=>A.$('#cartDrawer').classList.add('open')); A.$('#closeCart')?.addEventListener('click',()=>A.$('#cartDrawer').classList.remove('open')); window.addEventListener('cart:changed',()=>this.render()); this.render(); },
    view(){ const cart=this.items(); const sub=cart.reduce((a,i)=>a+i.qty*i.price,0); const t=A.totals(sub); return `<section class="section container"><div class="section-head"><div><p class="eyebrow">Checkout</p><h1>Your Cart</h1><p>PRICES ARE NOT FIXED. Tax 10% dan service 5% diterapkan.</p></div></div><div class="grid grid-2"><div class="card">${cart.length?cart.map(i=>`<div class="cart-row"><img src="${A.escape(i.image_url||A.placeholder())}"><div><strong>${A.escape(i.name)}</strong><p>${i.qty} × ${A.formatRupiah(i.price)}</p></div><strong>${A.formatRupiah(i.qty*i.price)}</strong></div>`).join(''):A.empty('Tambahkan menu terlebih dahulu.')}</div><form id="checkoutForm" class="card form"><h2>Place order</h2><label class="field">Order type<select name="order_type"><option>dine_in</option><option>takeaway</option><option>delivery</option></select></label><label class="field">Catatan<textarea name="notes"></textarea></label><div class="summary-box"><p>Subtotal ${A.formatRupiah(t.subtotal)}</p><p>Tax 10% ${A.formatRupiah(t.tax)}</p><p>Service 5% ${A.formatRupiah(t.service)}</p><h3>Total ${A.formatRupiah(t.total)}</h3></div><button class="btn btn-primary" ${cart.length?'':'disabled'}>Place order</button></form></div></section>`; }
  };
})(window.Amino = window.Amino || {});
