(function(A){
  A.checkout = {
    bind(){ A.$('#checkoutForm')?.addEventListener('submit',e=>this.place(e,false)); A.$('#bookingForm')?.addEventListener('submit',e=>this.book(e)); A.$('#orderType')?.addEventListener('change',()=>this.toggleFields()); A.$('#whatsappOrder')?.addEventListener('click',()=>this.whatsapp(false)); A.$('#saveWhatsapp')?.addEventListener('click',()=>this.whatsapp(true)); A.$('#copyCartText')?.addEventListener('click',()=>A.copyText(A.cart.buildWhatsAppText(this.formObject()))); A.$('#useLocation')?.addEventListener('click',()=>this.useLocation()); A.$$('.cart-note').forEach(n=>n.addEventListener('change',()=>A.cart.setNote(n.dataset.id,n.value))); this.toggleFields(); },
    formObject(){ const form=A.$('#checkoutForm'); return form?Object.fromEntries(new FormData(form).entries()):{}; },
    toggleFields(){ const type=A.$('#orderType')?.value; A.$$('.delivery-field').forEach(el=>el.classList.toggle('hidden',type!=='delivery')); A.$$('.dine-field').forEach(el=>el.classList.toggle('hidden',type!=='dine_in')); },
    validate(data){ if(data.order_type==='dine_in' && !data.table_number) return 'Table number wajib untuk dine in.'; if(data.order_type==='delivery' && !data.delivery_address) return 'Alamat wajib untuk delivery.'; return null; },
    async useLocation(){ if(!navigator.geolocation) return A.toast('Geolocation tidak tersedia.','error'); navigator.geolocation.getCurrentPosition(pos=>{ A.$('[name="delivery_lat"]').value=pos.coords.latitude; A.$('[name="delivery_lng"]').value=pos.coords.longitude; A.$('#locationStatus').textContent='Lokasi tersimpan.'; A.toast('Lokasi delivery tersimpan.','success'); },()=>A.toast('Gagal mengambil lokasi.','error')); },
    async saveOrder(){ if(!await A.auth.requireLogin()) return null; const cart=A.cart.items(); if(!cart.length) return null; const data=this.formObject(); const invalid=this.validate(data); if(invalid){ A.toast(invalid,'error'); return null; } const totals=A.cart.summary(); const order={user_id:A.auth.user.id,status:'pending',order_type:data.order_type,customer_name:data.customer_name,customer_phone:data.customer_phone,table_number:data.table_number||null,delivery_address:data.delivery_address||null,delivery_lat:data.delivery_lat||null,delivery_lng:data.delivery_lng||null,payment_method:data.payment_method,notes:data.notes,subtotal:totals.subtotal,tax:totals.tax,service_fee:totals.service,total:totals.total}; const {data:created,error}=await A.supabase.from('orders').insert(order).select().single(); if(error){ A.toast(error.message,'error'); return null; } const rows=cart.map(i=>({order_id:created.id,menu_item_id:i.id,item_name:i.name,variant_name:i.variant_name,quantity:i.qty,unit_price:i.price,total_price:i.price*i.qty,note:i.note||null})); const itemRes=await A.supabase.from('order_items').insert(rows); if(itemRes.error){ A.toast(itemRes.error.message,'error'); return null; } A.storage.clearCart(); await A.notifyFunction({type:'order',id:created.id,event:'new_order'}); return created; },
    async place(e){ e.preventDefault(); const created=await this.saveOrder(); if(created){ A.toast('Order masuk ke Supabase.','success'); location.hash='#/orders'; } },
    async whatsapp(saveFirst){ const text=A.cart.buildWhatsAppText(this.formObject()); if(saveFirst){ const created=await this.saveOrder(); if(!created) return; } A.openWhatsApp(text); },
    async book(e){ e.preventDefault(); if(!await A.auth.requireLogin()) return; const f=new FormData(e.target); const row=Object.fromEntries(f.entries()); row.user_id=A.auth.user.id; row.status='pending'; const {data,error}=await A.supabase.from('bookings').insert(row).select().single(); if(error) return A.toast(error.message,'error'); await A.notifyFunction({type:'booking',id:data.id,event:'new_booking'}); A.toast('Booking terkirim.','success'); e.target.reset(); }
  };
  A.bookingView = () => `<section class="section container split-section"><div><p class="eyebrow">Reservation</p><h2>Book table</h2><p class="lead">Pilih waktu terbaik. Admin akan mendapat notifikasi dan mengonfirmasi.</p></div><form id="bookingForm" class="card form"><label class="field">Tanggal<input name="booking_date" type="date" required></label><label class="field">Jam<input name="booking_time" type="time" required></label><label class="field">Jumlah tamu<input name="party_size" type="number" min="1" value="2" required></label><label class="field">Catatan<textarea name="notes"></textarea></label><button class="btn btn-primary">Book table</button></form></section>`;
})(window.Amino = window.Amino || {});
