(function(A){
  A.menu = { items:[], categories:[], promos:[], loading:false,
    async load(){ if(!A.supabase) return; this.loading=true; const [cats,items,promos]=await Promise.all([A.supabase.from('categories').select('*').eq('is_active',true).order('sort_order'), A.supabase.from('menu_items').select('*, item_variants(*)').eq('is_available',true).order('sort_order'), A.supabase.from('promos').select('*').eq('is_active',true).order('created_at',{ascending:false}).limit(4)]); this.categories=cats.data||[]; this.items=items.data||[]; this.promos=promos.data||[]; this.loading=false; },
    price(item){ return item.item_variants?.length?Math.min(...item.item_variants.map(v=>v.price)):item.price; },
    card(item){ const variants=item.item_variants||[]; const badges=[item.is_best_seller?'Best Seller':'',item.is_recommended||item.is_featured?'Recommended':'',item.is_new?'New':''].filter(Boolean); return `<article class="card menu-card" data-category="${item.category_id}"><div class="menu-art"><img class="menu-image" src="${A.escape(item.image_url||A.placeholder())}" alt="${A.escape(item.name)}"><div class="menu-badges">${badges.map(b=>`<span>${b}</span>`).join('')}</div></div><div class="menu-body"><span class="pill">${A.escape(item.dietary_label||'Amino Bali')}</span><h3>${A.escape(item.name)}</h3><p>${A.escape(item.description||'Fresh natural luxury dish by Amino Resto Bali.')}</p>${variants.length?`<select class="variant-select" data-id="${item.id}">${variants.map(v=>`<option value="${v.id}">${A.escape(v.name)} — ${A.formatRupiah(v.price)}</option>`).join('')}</select>`:''}</div><div class="menu-actions"><strong class="price">${variants.length?'from ':''}${A.formatRupiah(this.price(item))}</strong><button class="btn btn-ghost quick-view" data-id="${item.id}">Quick view</button><button class="btn btn-primary add-cart" data-id="${item.id}">Add to cart</button></div></article>`; },
    view(full=false){ const list=this.items.slice(0, full?999:8); return `<section class="section container"><div class="section-head"><div><p class="eyebrow">${full?'Catalog Menu':'Best Seller'}</p><h2>${full?'Amino Resto Bali Menu':'Favorite natural luxury plates'}</h2><p>PRICES ARE NOT FIXED. Tax 10% dan service 5% dihitung saat checkout dan receipt.</p></div>${full?'':'<a class="btn btn-ghost" href="#/menu">View full menu</a>'}</div>${this.promos.length?`<div class="promo-strip">${this.promos.map(p=>`<div class="promo-card"><strong>${A.escape(p.title)}</strong><span>${A.escape(p.description||p.code||'Admin managed promo')}</span></div>`).join('')}</div>`:''}${full?`<div class="category-bar"><button class="btn btn-ghost category-filter active" data-cat="all">All</button>${this.categories.map(c=>`<button class="btn btn-ghost category-filter" data-cat="${c.id}">${A.escape(c.name)}</button>`).join('')}</div>`:''}<div id="menuGrid" class="grid menu-grid">${this.loading?A.skeleton(6):(list.length?list.map(i=>this.card(i)).join(''):A.empty('Menu segera hadir. Placeholder tetap tampil sampai data Supabase diisi.'))}</div></section>`; },
    bind(){ A.$$('.add-cart').forEach(b=>b.addEventListener('click',()=>{ const item=this.items.find(i=>i.id===b.dataset.id); const selected=A.$(`.variant-select[data-id="${b.dataset.id}"]`)?.value; const variant=item?.item_variants?.find(v=>v.id===selected); A.cart.add(item,variant); })); A.$$('.quick-view').forEach(b=>b.addEventListener('click',()=>this.quick(b.dataset.id))); A.$$('.category-filter').forEach(b=>b.addEventListener('click',()=>{ A.$$('.category-filter').forEach(x=>x.classList.remove('active')); b.classList.add('active'); const list=b.dataset.cat==='all'?this.items:this.items.filter(i=>i.category_id===b.dataset.cat); A.$('#menuGrid').innerHTML=list.length?list.map(i=>this.card(i)).join(''):A.empty('Kategori ini belum memiliki menu.'); this.bind(); A.bindRipples(A.$('#menuGrid')); })); },
    quick(id){ const item=this.items.find(i=>i.id===id); if(!item) return; const variants=(item.item_variants||[]).map(v=>`<label class="variant-option"><input type="radio" name="quickVariant" value="${v.id}" ${v===item.item_variants[0]?'checked':''}> ${A.escape(v.name)} <strong>${A.formatRupiah(v.price)}</strong></label>`).join(''); A.openModal(`<button class="icon-button modal-close" onclick="Amino.closeModal()">×</button><div class="quick-grid"><img class="menu-image large" src="${A.escape(item.image_url||A.placeholder())}" alt=""><div><p class="eyebrow">Quick view</p><h2>${A.escape(item.name)}</h2><p>${A.escape(item.description||'')}</p><div class="variant-list">${variants||`<strong class="price">${A.formatRupiah(item.price)}</strong>`}</div><p class="notice"><strong>PRICES ARE NOT FIXED.</strong> Tax 10%, service 5%.</p><button class="btn btn-primary add-cart-modal">Add to cart</button></div></div>`); A.$('.add-cart-modal')?.addEventListener('click',()=>{ const val=A.$('[name="quickVariant"]:checked')?.value; A.cart.add(item,item.item_variants?.find(v=>v.id===val)); A.closeModal();}); }
  };
})(window.Amino = window.Amino || {});
