(function(A){
  A.menu = { items:[], categories:[],
    async load(){ if(!A.supabase) return; const [cats,items]=await Promise.all([A.supabase.from('categories').select('*').eq('is_active',true).order('sort_order'), A.supabase.from('menu_items').select('*, item_variants(*)').eq('is_available',true).order('name')]); this.categories=cats.data||[]; this.items=items.data||[]; },
    card(item){ const price=item.item_variants?.length?item.item_variants[0].price:item.price; return `<article class="card menu-card"><img class="menu-image" src="${A.escape(item.image_url||A.placeholder())}" alt="${A.escape(item.name)}"><div><span class="pill">${A.escape(item.dietary_label||'Chef selection')}</span><h3>${A.escape(item.name)}</h3><p>${A.escape(item.description||'Natural luxury dish by Amino Resto.')}</p></div><div class="action-row"><strong class="price">${A.formatRupiah(price)}</strong><button class="btn btn-ghost quick-view" data-id="${item.id}">Quick view</button><button class="btn btn-primary add-cart" data-id="${item.id}">Add to cart</button></div></article>`; },
    view(full=false){ const cats=['all',...this.categories.map(c=>c.slug)]; const list=this.items.slice(0, full?999:6); return `<section class="section container"><div class="section-head"><div><p class="eyebrow">${full?'Full Menu':'Menu Preview'}</p><h2>PRICES ARE NOT FIXED</h2><p>Tax 10% dan service 5% akan dihitung saat checkout dan receipt.</p></div>${full?'':'<a class="btn btn-ghost" href="#/menu">View full menu</a>'}</div>${full?`<div class="category-bar">${cats.map((c,i)=>`<button class="btn btn-ghost category-filter ${i?'':'active'}" data-cat="${c}">${c}</button>`).join('')}</div>`:''}<div id="menuGrid" class="grid grid-3">${list.length?list.map(i=>this.card(i)).join(''):A.empty('Menu segera hadir. Placeholder tetap tampil sampai data Supabase diisi.')}</div></section>`; },
    bind(){ A.$$('.add-cart').forEach(b=>b.addEventListener('click',()=>A.cart.add(this.items.find(i=>i.id===b.dataset.id)))); A.$$('.quick-view').forEach(b=>b.addEventListener('click',()=>this.quick(b.dataset.id))); A.$$('.category-filter').forEach(b=>b.addEventListener('click',()=>{ A.$$('.category-filter').forEach(x=>x.classList.remove('active')); b.classList.add('active'); const cat=b.dataset.cat; const list=cat==='all'?this.items:this.items.filter(i=>this.categories.find(c=>c.id===i.category_id)?.slug===cat); A.$('#menuGrid').innerHTML=list.length?list.map(i=>this.card(i)).join(''):A.empty('Kategori ini belum memiliki menu.'); this.bind(); })); },
    quick(id){ const item=this.items.find(i=>i.id===id); if(!item) return; const variants=(item.item_variants||[]).map(v=>`<li>${A.escape(v.name)} - ${A.formatRupiah(v.price)}</li>`).join(''); A.openModal(`<button class="icon-button" style="float:right" onclick="Amino.closeModal()">×</button><img class="menu-image" src="${A.escape(item.image_url||A.placeholder())}" alt=""><h2>${A.escape(item.name)}</h2><p>${A.escape(item.description||'')}</p><ul>${variants}</ul><p><strong>PRICES ARE NOT FIXED.</strong> Tax 10%, service 5%.</p><button class="btn btn-primary add-cart-modal">Add to cart</button>`); A.$('.add-cart-modal')?.addEventListener('click',()=>{A.cart.add(item); A.closeModal();}); }
  };
})(window.Amino = window.Amino || {});
